[tools]
deno = "2.2.10"
direnv = "2.36.0"
elixir = "1.18.4-otp-28"
erlang = "28.0.1"
gleam = "1.11.1"
go = "1.24.2"
just = "1.40.0"
kubectl = "1.32.3"
node = "25.2.1"
python = "3.13.3"
ruby = "3.4.3"
zig = "0.14.1"
